// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADyoU0kjC8i_oO9ju2_ZI1ibAcJjdBE-w',
    appId: '1:417768617478:web:6d95dd1373bf18d22ff587',
    messagingSenderId: '417768617478',
    projectId: 'chat-app-demo-da5a9',
    authDomain: 'chat-app-demo-da5a9.firebaseapp.com',
    storageBucket: 'chat-app-demo-da5a9.appspot.com',
    measurementId: 'G-S5L9L8HWK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7vzGGkUx8gNh5eNFyQenaDl6CcqRmS8',
    appId: '1:417768617478:android:ae1a53acd2ddfd152ff587',
    messagingSenderId: '417768617478',
    projectId: 'chat-app-demo-da5a9',
    storageBucket: 'chat-app-demo-da5a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY4YHOWAqica4tR-NcBP8lFDMBazXJGsU',
    appId: '1:417768617478:ios:027826e42404d0822ff587',
    messagingSenderId: '417768617478',
    projectId: 'chat-app-demo-da5a9',
    storageBucket: 'chat-app-demo-da5a9.appspot.com',
    iosClientId: '417768617478-k6bgll19l7ov28dg3889vafqhnrdfd28.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemoFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY4YHOWAqica4tR-NcBP8lFDMBazXJGsU',
    appId: '1:417768617478:ios:027826e42404d0822ff587',
    messagingSenderId: '417768617478',
    projectId: 'chat-app-demo-da5a9',
    storageBucket: 'chat-app-demo-da5a9.appspot.com',
    iosClientId: '417768617478-k6bgll19l7ov28dg3889vafqhnrdfd28.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppDemoFlutter',
  );
}
